import assert from "node:assert/strict";
import {createDefaultStrategy, cloneStrategy, pinStrategyFeeder, strategyResourcePorts, validateStrategy, type StrategyDocument} from "../src/app/strategy-model";
import {EditHistory} from "../src/app/edit-history";
import {strategyStructuralSignature} from "../src/app/strategy-eval-presentation";

const child = createDefaultStrategy();
child.solver_policy_scope = "gated_search_with_paid_root_foulborn_salvage_v2";
child.output_contracts = [{id: "ready", base_key: child.base_state.base_key, predicate: {type: "rarity_is", rarity: "rare"}}];
const saved = {id: "saved-child", name: "Child", revision: "r1", createdAt: 1, strategy: child};
const parent = createDefaultStrategy();
parent.resources = [pinStrategyFeeder("feeder", saved, "ready")];
parent.nodes[1].operation = {type: "invoke_feeder", params: {resource_id: "feeder"}};
assert.deepEqual(validateStrategy(parent).filter(issue => issue.severity === "error"), []);
assert.deepEqual(strategyResourcePorts(parent.nodes[1]), {inputs: [], outputs: ["feeder"]});

const frozen = parent.resources[0].feeder!.document_json;
child.base_state.rarity = "normal";
saved.revision = "r2";
assert.equal(parent.resources[0].feeder!.document_json, frozen);
assert.equal(parent.resources[0].feeder!.revision, "r1");
assert.deepEqual(JSON.parse(JSON.stringify(cloneStrategy(parent))).resources, parent.resources);
const history = new EditHistory<StrategyDocument>();
history.reset(parent);
const edited = cloneStrategy(parent);
edited.nodes[1].operation = {type: "move_resource", params: {from: "feeder", to: "current"}};
history.record(edited);
assert.equal(history.go(0)!.resources![0].feeder!.document_json, frozen);
assert.equal(history.go(1)!.nodes[1].operation!.type, "move_resource");
const restored = new EditHistory<StrategyDocument>();
restored.restore(JSON.parse(JSON.stringify(history.export())), edited);
assert.equal(restored.go(0)!.resources![0].feeder!.revision, "r1");

const invalid = cloneStrategy(parent);
invalid.resources![0].feeder!.output_contract_id = "missing";
assert.ok(validateStrategy(invalid).some(issue => issue.message.includes("missing")));
invalid.resources![0].feeder!.document_json = "{";
assert.ok(validateStrategy(invalid).some(issue => issue.severity === "error"));
const cycle = cloneStrategy(parent);
cycle.resources![0].feeder!.document_json = JSON.stringify({...parent, output_contracts: child.output_contracts});
assert.ok(validateStrategy(cycle).some(issue => issue.message.includes("cycle")));
const conflict = cloneStrategy(parent);
conflict.resources!.push({...cloneStrategy(parent).resources![0], id: "other"});
conflict.resources![1].feeder!.document_json = JSON.stringify(child);
assert.ok(validateStrategy(conflict).some(issue => issue.message.includes("conflicting")));
const selfMove = cloneStrategy(parent);
selfMove.nodes[1].operation = {type: "move_resource", params: {from: "feeder", to: "feeder"}};
assert.ok(validateStrategy(selfMove).some(issue => issue.message.includes("distinct")));
assert.notEqual(strategyStructuralSignature(parent), strategyStructuralSignature(edited));
const recombination = cloneStrategy(parent);
recombination.nodes[1].operation = {type: "recombination", params: {input_a: "feeder", input_b: "current", output: "feeder"}};
assert.ok(validateStrategy(recombination).some(issue => issue.code === "recombination-held"));
assert.deepEqual(strategyResourcePorts(recombination.nodes[1]), {inputs: ["feeder", "current"], outputs: ["feeder"]});
assert.throws(() => pinStrategyFeeder("x", saved, "missing"));
console.log("Strategy feeder pinning, output contracts, item ports and history checks passed.");
